num_classes: 1001
checkpoint_path: "try_inference/best_model_841.pkl"
batch_size: 1
max_epochs: 10
learning_rate: 0.00001
train_folder_path: "data/training_set"
val_folder_path: "data/validation_set"
most_common_answers_file_path: "data/most_common_train_answers.json"
log_dir: "runs"
save_checkpoint_path: training1
